#!/usr/bin/env node
require('shelljs/global');
var argv = require('yargs').argv;
var colors = require('colors')

var config = [{
  tarName : 'btc.tar.gz',
  staticPage : 'sfq.html',
  type : 1,
  buildCli : 'npm run deploy:prod'
},{
  tarName : 'ltc.tar.gz',
  staticPage : 'cbq.html',
  type : 2,
  buildCli : 'npm run deploy:prodlt'
},{
  tarName : 'dash.tar.gz',
  staticPage : 'cbq.html',
  type : 3,
  buildCli : 'npm run deploy:prodds'
},{
  tarName : 'doge.tar.gz',
  staticPage : 'cbq.html',
  type : 4,
  buildCli : 'npm run deploy:prodgb'
},{
  tarName : 'moon.tar.gz',
  staticPage : 'cbq.html',
  type : 5,
  buildCli : 'npm run deploy:prodmn'
},{
  tarName : 'auto.tar.gz',
  staticPage : 'gbq.html',
  type : 6,
  buildCli : 'npm run deploy:prodat'
}]

// for(var i=0,l=config.lenght ; i<l ; i++){
//   rm('-rf',config[i].tarName);
// }

if(argv.type){
  build(config[argv.type-1].type,config[argv.type-1].buildCli,config[argv.type-1].tarName,config[argv.type-1].staticPage);
  var ssh = 'scp '+config[0].tarName+' root@123.56.129.175:/data/www/solebtc';
  exec(ssh);
}else{
  buildAll()
}

function buildAll(){
  for(var i=0,l=config.length ; i<l ; i++){
    var _this = config[i];
    rm('-rf',_this.tarName);
    build(_this.type,_this.buildCli,_this.tarName);
  }
}

function build(type,buildCli,name,staticPage){
  exec('cp  '+staticPage+' dist')
  console.log(colors.green('build '+name+' begin'));
  exec('export TYPE='+type);
  exec(buildCli);
  exec('cp '+staticPage+' dist');
  exec('tar -czvf '+name+' dist');
  console.log(colors.green('build '+name+' end'));
}
